name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - 'app-api/**'

  pull_request:
    branches:
      - main
    paths:
      - 'infra/**'
      - 'app-api/**'

  workflow_dispatch:

jobs:
  build-infrastructure:
    name: Build Bicep Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Validate bicep
        run: |
          cd infra/azure
          az bicep install
          az bicep build -f main.bicep
          az bicep build-params -f main.bicepparam --outfile parameters.json

      - name: Upload infrastructure artifact
        uses: actions/upload-artifact@v6
        with:
          name: infra
          path: infra/azure/*.json
          if-no-files-found: error

  build-api:
    name: Build API Project
    runs-on: ubuntu-latest
    env:
      API_PROJECT_PATH: WeightTracker.Api/WeightTracker.Api.csproj
      WORKING_DIRECTORY: app-api
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: ${{ env.WORKING_DIRECTORY }}/global.json

      - name: Set credentials for GitHub source
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          dotnet nuget update source github \
            --username "${{ github.repository_owner }}" \
            --password "${{ secrets.GITHUB_TOKEN }}" \
            --store-password-in-clear-text

      - name: Restore dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: dotnet restore

      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: dotnet build --configuration Release --no-restore

      - name: Test
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: dotnet test -c Release --no-build

      - name: Publish
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: dotnet publish ${{ env.API_PROJECT_PATH }} --no-build --configuration Release --output webapp

      - name: Upload API artifact
        uses: actions/upload-artifact@v6
        with:
          name: webapp
          path: ${{ env.WORKING_DIRECTORY }}/webapp/**
          if-no-files-found: error

  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: [build-infrastructure, build-api]
    environment: prod
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download infrastructure artifact
        uses: actions/download-artifact@v7
        with:
          name: infra
          path: infra

      - name: Deploy infrastructure
        run: |
          az deployment group create \
            --resource-group ${{ vars.RESOURCE_GROUP_NAME }} \
            --template-file infra/main.json \
            --parameters infra/parameters.json

  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    needs: [deploy-infrastructure, build-api]
    environment: prod
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download API artifact
        uses: actions/download-artifact@v7
        with:
          name: webapp
          path: webapp

      - name: Deploy API
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.APP_NAME }}
          package: webapp
